"""
Dummy Generator Stage

Generates all dummy/stub files needed for compilation of subsequent stages.
This must run FIRST before any other stage that compiles code.

Inputs:
  - config/graph_fields.config

Outputs:
  - include/generated/graph.cuh (stub)
  - include/generated/gpu_graph.cuh (stub)
  - include/generated/fill_dummy.cuh (empty placeholder)
  - include/generated/get_max_weight.cuh (empty placeholder)
  - include/generated/get_sum_weight.cuh (empty placeholder)
  - include/generated/walker_traits.cuh (empty placeholder)
"""

from pathlib import Path
from ..base import PipelineStage, PipelineError
from ..graph_config_parser import GraphFieldsConfigParser


class DummyGenerator(PipelineStage):
    """
    Generate all dummy/stub files for compilation.

    Creates minimal stub versions of graph.cuh and gpu_graph.cuh that contain
    only field declarations, plus empty placeholder headers for files that
    will be generated by CodeGenerator.

    These files are needed for:
    1. MetadataExtractor to compile app.cuh
    2. LLVMAnalyzer to compile walker_template.cu

    All files will be overwritten by CodeGenerator in the final stage with
    complete implementations.
    """

    def __init__(self, config):
        super().__init__(config)

    @property
    def name(self) -> str:
        """Return the name of this stage."""
        return "DummyGenerator"

    @property
    def dependencies(self):
        """Return list of required input files/directories."""
        return [
            self.config.graph_fields_config,  # config/graph_fields.config
        ]

    @property
    def outputs(self):
        """Return list of expected output files."""
        return [
            self.config.get_generated_path('graph'),
            self.config.get_generated_path('gpu_graph'),
            self.config.generated_dir / "fill_dummy.cuh",
            self.config.generated_dir / "get_max_weight.cuh",
            self.config.generated_dir / "get_sum_weight.cuh",
            self.config.generated_dir / "walker_traits.cuh",
        ]

    def execute(self):
        """Generate all dummy files."""
        self.logger.info("Generating dummy header files...")

        # Ensure directories exist
        self.config.ensure_artifacts_dir()
        self.config.ensure_generated_dir()

        # Load graph fields configuration
        fields_config = GraphFieldsConfigParser(str(self.config.graph_fields_config))

        additional_fields = {}
        if fields_config.is_loaded():
            for field_name in fields_config.get_all_fields():
                field_def = fields_config.get_field_definition(field_name)
                additional_fields[field_name] = field_def.data_type
            self.logger.info(f"Loaded {len(additional_fields)} additional fields from config")
        else:
            self.logger.info("No additional fields configured")

        # Generate stubs
        self._generate_graph_stub(additional_fields)
        self._generate_gpu_graph_stub(additional_fields)
        self._generate_dummy_headers()

        self.logger.info("Dummy file generation complete")

    def _generate_graph_stub(self, additional_fields):
        """Generate graph.cuh stub for host graph."""
        output_file = self.config.generated_dir / "graph.cuh"

        try:
            with open(output_file, "w") as f:
                f.write("#pragma once\n\n")
                f.write("#include \"graph_base.cuh\"\n\n")
                f.write("// Stub graph class for LLVM analysis\n")
                f.write("// This will be replaced by the full generated version in CodeGenerator stage\n")
                f.write("class graph : public graph_base {\n")
                f.write("  public:\n")

                # Add fields from config
                for field_name, data_type in additional_fields.items():
                    f.write(f"    {data_type}* {field_name} = nullptr;\n")

                f.write("\n  public:\n")
                f.write("    graph() : graph_base() {}\n")
                f.write("    graph(const char* xadj_file, const char* adjncy_file, const char* weight_file, const char* config_file = nullptr)\n")
                f.write("        : graph_base(xadj_file, adjncy_file, weight_file) {}\n")
                f.write("};\n")

            self.logger.info(f"Generated graph stub: {output_file}")

        except IOError as e:
            raise PipelineError(f"Failed to write graph stub: {e}")

    def _generate_gpu_graph_stub(self, additional_fields):
        """Generate gpu_graph.cuh stub for GPU graph."""
        output_file = self.config.generated_dir / "gpu_graph.cuh"

        try:
            with open(output_file, "w") as f:
                f.write("#pragma once\n\n")
                f.write("#include \"gpu_graph_base.cuh\"\n")
                f.write("#include \"generated/graph.cuh\"\n\n")
                f.write("// Stub gpu_graph class for LLVM analysis\n")
                f.write("// This will be replaced by the full generated version in CodeGenerator stage\n")
                f.write("class gpu_graph : public gpu_graph_base {\n")
                f.write("  public:\n")

                # Add fields from config
                for field_name, data_type in additional_fields.items():
                    f.write(f"    {data_type}* {field_name} = nullptr;\n")

                f.write("\n  public:\n")
                f.write("    gpu_graph() : gpu_graph_base() {}\n")
                f.write("    explicit gpu_graph(graph* ginst) : gpu_graph_base(ginst) {}\n")
                f.write("};\n")

            self.logger.info(f"Generated gpu_graph stub: {output_file}")

        except IOError as e:
            raise PipelineError(f"Failed to write gpu_graph stub: {e}")

    def _generate_dummy_headers(self):
        """Generate empty dummy headers for files that will be generated by CodeGenerator."""
        dummy_headers = [
            "fill_dummy.cuh",
            "get_max_weight.cuh",
            "get_sum_weight.cuh",
            "walker_traits.cuh"
        ]

        for header_name in dummy_headers:
            output_file = self.config.generated_dir / header_name
            try:
                with open(output_file, "w") as f:
                    f.write(f"#pragma once\n")
                    f.write(f"// Placeholder for {header_name}\n")
                    f.write(f"// This will be generated by CodeGenerator stage\n")
                self.logger.info(f"Generated dummy header: {output_file}")
            except IOError as e:
                raise PipelineError(f"Failed to write dummy header {header_name}: {e}")
